image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update -qq && apt-get install -y -qq libnss3 libnss3-dev libgl1
  - python3 -V              # Print out python version for debugging
  - python3 -m pip install --upgrade pip
  - python3 -m pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

pylava:
  stage: build
  image: alpine:latest
  before_script:
    - apk update && apk add python3
    - python3 -m pip install --upgrade pip && python3 -m pip install pylava
    - pylava --version
  script:
    - ci/pylava.sh

pylint:
  stage: build
  image: alpine:latest
  before_script:
    - apk update && apk add python3 python3-dev py3-qt5 build-base
    - python3 -m pip install --upgrade pip && python3 -m pip install pylint
    - pylint --version
  script:
    - ci/pylint.sh

tests:
  stage: test
  script:
    - apt-get install -y -qq software-properties-common python3-dev xvfb qt5-default
    - python3 -m pip --version
    - chmod +x build_test.sh
  after_script:
    - ./configure.sh 
    - python3 -m pip install pyvirtualdisplay
    - nohup python3 Tests/server_tester.py &
    - python3 Tests/program_tester.py

pages:
  stage: deploy
  tags:
    - trd-runner
  script:
    - python3 -m pip install sphinx recommonmark groundwork-sphinx-theme
    - python3 -m pip install -r requirements.txt
  after_script:
    - sphinx-build --color -b html docs/source public
    - sphinx-build --color -b coverage docs/source coverage
  artifacts:
    paths:
    - public
  only:
    - master
