image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V               # Print out python version for debugging
  - apt-get update -qy
  - apt-get install -y -qq software-properties-common python3 python3-dev python3-pip xvfb qt5-default libnss3 libnss3-dev libgl1
  - pip3 install --upgrade pip
  - pip3 install virtualenv sphinx
  - virtualenv venv
  - source venv/bin/activate
  - chmod +x build_test.sh

tests:
  stage: test
  script: 
    - ./configure.sh 
    - pip3 install pyvirtualdisplay
    - nohup python3 Tests/server_tester.py &
    - python3 Tests/program_tester.py

pages:
  stage: deploy
  script:
    - mkdir public
    - cd docs/source
    - make html
    - mv ../build/html/* ../../public
  artifacts:
    paths:
    - public
  only:
  - master
