image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V               # Print out python version for debugging
  - apt-get update -qq && apt-get install -y -qq python3 python3-pip
  - apt-get install -y -qq libnss3 libnss3-dev libgl1
  - pip3 install --upgrade pip

tests:
  stage: test
  tags:
    - trd-runner
  before_script:
    - apt-get update -qq && apt-get install -y -qq software-properties-common python3-dev xvfb qt5-default
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - chmod +x build_test.sh
  script: 
    - ./configure.sh 
    - pip3 install pyvirtualdisplay
    - nohup python3 Tests/server_tester.py &
    - python3 Tests/program_tester.py

pages:
  stage: deploy
  tags:
    - trd-runner
  before_script:
    - pip3 install sphinx
    - pip3 install -r requirements.txt
  script:
    - sphinx-build -b html docs/source public
    - sphinx-build -b coverage docs/source coverage

  artifacts:
    paths:
    - public
  only:
  - master

pylava:
  stage: build
  before_script:
    - pip3 install pylava
  script:
    - ci/pylava.sh
