image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V               # Print out python version for debugging
  - apt-get update -qy
  - apt-get install -y -qq python3 python3-pip
  - pip3 install --upgrade pip

tests:
  stage: test
  before_script:
    - apt-get install -y -qq software-properties-common python3 python3-dev python3-pip xvfb qt5-default libnss3 libnss3-dev libgl1
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - chmod +x build_test.sh
  script: 
    - ./configure.sh 
    - pip3 install pyvirtualdisplay
    - nohup python3 Tests/server_tester.py &
    - python3 Tests/program_tester.py

documentation:
  stage: deploy
  before_script:
    - pip3 install sphinx
    - pip3 install -r requirements.txt
    - mkdir public
  script:
    - cd docs
    - sphinx-build -b html source build
    - sphinx-build -b coverage source ../coverage
    - cp -r build/html/* ../public
  artifacts:
    paths:
    - public
  only:
  - master
