language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
    -DISPLAY=":99.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - chmod +x build_test.sh
install:
  - pip install -r requirements.txt
before_script:
  - nohup python3 Tests/server_tester.py &
script:
  - ./build_test.sh
after_success:
  - coveralls
