Logging:
  version: 1
  disable_existing_loggers: True

  formatters:
    debugging:
      format: "%(asctime)s  [%(thread)12d] %(levelname)-8s - %(name)30s.%(funcName)-20s - %(message)s"
    mainFile:
      format: "%(asctime)s  [%(name)30s.%(funcName)-18s]  %(levelname)-8s -  %(message)s"
    brief:
      format: "%(levelname)-8s [%(thread)d] - %(name)30s.%(funcName)-20s - %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      formatter: brief
      level: DEBUG
      stream: ext://sys.stderr
    debugFile:
      class: logging.FileHandler
      formatter: debugging
      level: DEBUG
      filename: logs/debugging_info.log
    radioTelescope:
      class: logging.handlers.TimedRotatingFileHandler
      formatter: mainFile
      level: WARNING
      filename: logs/RadioTelescope_Logger
      backupCount: 0
      atTime: None
      when: 'D'  # Rotate the file creation every day
      interval: 1
      encoding: 'utf-8'  # Set the file encoding to utf-8
      utc: True  # Set the time of file creation to be UTC
    radioTelescopeThread:
      class: CLogFileHandler.CustomLogHandler
      formatter: mainFile
      level: INFO
      filename: logs/RadioTelescope_Logger.log
      when: 'D'  # Rotate the file creation every day
      enc: 'utf-8'  # Set the file encoding to utf-8
      utc: True  # Set the time of file creation to be UTC

  # Configure the root logger
  root:
    level: INFO
    handlers: [console, debugFile, radioTelescopeThread]

