# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ManualControl.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManualControl(object):
    def __init__(self):
        self.manContWindow = QtWidgets.QMainWindow()
        self.setupUi(self.manContWindow)

    def setupUi(self, ManualControl):
        ManualControl.setObjectName("ManualControl")
        ManualControl.setWindowModality(QtCore.Qt.ApplicationModal)
        ManualControl.resize(244, 234)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        ManualControl.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ManualControl)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.raStepsField = QtWidgets.QSpinBox(self.groupBox)
        self.raStepsField.setMinimum(-400000)
        self.raStepsField.setMaximum(400000)
        self.raStepsField.setObjectName("raStepsField")
        self.horizontalLayout.addWidget(self.raStepsField)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.movRaBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movRaBtn.sizePolicy().hasHeightForWidth())
        self.movRaBtn.setSizePolicy(sizePolicy)
        self.movRaBtn.setObjectName("movRaBtn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.movRaBtn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.decStepsField = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decStepsField.sizePolicy().hasHeightForWidth())
        self.decStepsField.setSizePolicy(sizePolicy)
        self.decStepsField.setMinimum(-400000)
        self.decStepsField.setMaximum(400000)
        self.decStepsField.setObjectName("decStepsField")
        self.horizontalLayout_2.addWidget(self.decStepsField)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.movDecBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movDecBtn.sizePolicy().hasHeightForWidth())
        self.movDecBtn.setSizePolicy(sizePolicy)
        self.movDecBtn.setObjectName("movDecBtn")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.movDecBtn)
        self.syncMoveBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syncMoveBtn.sizePolicy().hasHeightForWidth())
        self.syncMoveBtn.setSizePolicy(sizePolicy)
        self.syncMoveBtn.setObjectName("syncMoveBtn")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.syncMoveBtn)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        ManualControl.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ManualControl)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 244, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        ManualControl.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ManualControl)
        self.statusbar.setObjectName("statusbar")
        ManualControl.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ManualControl)
        QtCore.QMetaObject.connectSlotsByName(ManualControl)

    def retranslateUi(self, ManualControl):
        _translate = QtCore.QCoreApplication.translate
        ManualControl.setWindowTitle(_translate("ManualControl", "Manual Control"))
        self.groupBox.setTitle(_translate("ManualControl", "Step Control"))
        self.label_3.setText(_translate("ManualControl",
                                        "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Total Steps</span></p></body></html>"))
        self.label_4.setText(_translate("ManualControl",
                                        "<html><head/><body><p><span style=\" font-weight:600;\">RA:</span></p></body></html>"))
        self.label_6.setText(_translate("ManualControl", "0"))
        self.label_5.setText(_translate("ManualControl",
                                        "<html><head/><body><p><span style=\" font-weight:600;\">DEC:</span></p></body></html>"))
        self.label_7.setText(_translate("ManualControl", "0"))
        self.label.setText(_translate("ManualControl",
                                      "<html><head/><body><p><span style=\" font-weight:600;\">RA  :</span></p></body></html>"))
        self.movRaBtn.setText(_translate("ManualControl", "MoveRA"))
        self.label_2.setText(_translate("ManualControl",
                                        "<html><head/><body><p><span style=\" font-weight:600;\">DEC:</span></p></body></html>"))
        self.movDecBtn.setText(_translate("ManualControl", "MoveDEC"))
        self.syncMoveBtn.setText(_translate("ManualControl", "MoveBoth"))
        self.menuFile.setTitle(_translate("ManualControl", "File"))

    def windShow(self):
        self.manContWindow.show()


